# ===== DATASOURCE - PostgreSQL (Render) =====
spring.datasource.url=${DATABASE_URL}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ===== JPA =====
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

# ===== H2 CONSOLE - wylaczone na produkcji =====
spring.h2.console.enabled=false

# ===== JWT =====
jwt.secret=${jwt.secret}
