server.port=8080

spring.datasource.url=jdbc:${DATABASE_URL}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

spring.h2.console.enabled=false

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970